# Generated by Django 6.0.3 on 2026-07-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_booking_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathroom',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('ensuite', 'Ensuite')], default='shared', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='bills_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('partial', 'Partially furnished')], default='furnished', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('flexible', 'Flexible')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('flexible', 'Flexible')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('room_in_house', 'Room in existing house'), ('whole_flat', 'Whole flat/house'), ('student_hostel', 'Student hostel'), ('homestay', 'Homestay')], default='room_in_house', max_length=20),
        ),
    ]
