# Generated by Django 6.0.3 on 2026-07-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_listing_available_from_listing_bathroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='booking',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('room', 'Room'), ('1bk', '1BK'), ('1bhk', '1BHK'), ('2bhk', '2BHK'), ('apartment', 'Apartment'), ('house', 'House'), ('flat', 'Flat'), ('hostel', 'Hostel'), ('hotel', 'Hotel'), ('cottage', 'Cottage')], default='room', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('message', models.TextField(blank=True, help_text='Message from seeker to owner')),
                ('owner_note', models.TextField(blank=True, help_text='Owner response / suggested time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='items.listing')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listing', 'seeker')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='visit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.visitrequest'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
